services:
  app:
    container_name: koios_app
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      args:
        APT_PACKAGES: ${APT_PACKAGES:-}
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8001:8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    container_name: koios_database
    image: pgvector/pgvector:pg17-trixie
    volumes:
      - /tmp/koios/data/db/:/var/lib/postgresql/data/
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./.env
    environment:
      POSTGRES_DB:       ${KOIOS_DB_NAME}
      POSTGRES_USER:     ${KOIOS_DB_USER}
      POSTGRES_PASSWORD: ${KOIOS_DB_PASS}
