[project]
name = "Koios Management Tools"
description = "Collection of tools to manage your Koios instance"
version = "0.1.0"
folder = koios_admin
authors = [
    "PidgeyL"
]

[python]
dependencies = [
]

[apt]
packages = [
]
