"""
Django settings for koios project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from itertools import chain
from pathlib   import Path

from  csp.constants import NONCE as CSP_NONCE
from  csp.constants import SELF  as CSP_SELF

from koios.functions import get_projects, get_plugin_app
from koios.config    import Config
conf = Config()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = conf.secret_key

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = conf.allowed_hosts


# Get custom app dependencies
CUSTOM_APP_DEPS = [get_plugin_app(app).plugin_meta.get('dependencies',{})
                       for app in get_projects()]

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third Party
    'tastypie',
    'csp',
]
[INSTALLED_APPS.append(app) for app in get_projects(with_deps=True)
    if app not in INSTALLED_APPS]

MIDDLEWARE = [
    # Third Party
    'csp.middleware.CSPMiddleware',
    # Default
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
for mid in chain(*[app.get('middleware',[]) for app in CUSTOM_APP_DEPS]):
    if mid not in MIDDLEWARE:
        MIDDLEWARE.append(mid)


ROOT_URLCONF = 'koios.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / 'templates' ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',
                'koios.context_processors.modular_nav',
                "csp.context_processors.nonce",
            ],
            "libraries": {
                "csp": "csp.templatetags.csp",
            }
        },
    },
]
for cont in chain(*[app.get('template_context_processors',[]) for app in CUSTOM_APP_DEPS]):
    if cont not in TEMPLATES[0]["OPTIONS"]["context_processors"]:
        TEMPLATES[0]["OPTIONS"]["context_processors"].append(cont)
for libs in [app.get('template_libraries',{}) for app in CUSTOM_APP_DEPS]:
    for key, val in libs.items():
        if key not in TEMPLATES[0]["OPTIONS"]["libraries"].keys():
            TEMPLATES[0]["OPTIONS"]["libraries"][key] = val
        else:
            print(f"Key already exists: {key}")
            #TODO: Logging


WSGI_APPLICATION = 'koios.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE':   conf.database_engine,
        'NAME':     conf.database_name,
        'USER':     conf.database_user,
        'PASSWORD': conf.database_password,
        'HOST':     conf.database_host,
        'PORT':     conf.database_port
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]
for auth in chain(*[app.get('authentication_backends',[]) for app in CUSTOM_APP_DEPS]):
    if auth not in AUTHENTICATION_BACKENDS:
        AUTHENTICATION_BACKENDS.append(auth)

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL       = 'static/'
STATIC_ROOT      = STATIC_URL
STATICFILES_DIRS = [ BASE_DIR / "static_files" ] # project-wide static files

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Media Storage
MEDIA_URL = '/media/'         # URL prefix for serving files
MEDIA_ROOT = conf.media_path  # absolute path on disk

# Koios Settings
LANDINGPAGE = conf.landingpage_view

# Custom Security Headers
# Disable MIME detection
SECURE_CONTENT_TYPE_NOSNIFF = conf.disable_mime_sniffing

# Add extra variables from apps
for vars in [app.get('extra_vars',{}) for app in CUSTOM_APP_DEPS]:
    for k, v in vars.items():
        locals()[k] = v


def parse_csp(settings):
    new_settings = []
    for s in settings:
        if s.lower() == "nonce":
            new_settings.append(CSP_NONCE)
        elif s.lower() in ["self", "'self'"]:
            new_settings.append(CSP_SELF)
        else:
            new_settings.append(s)
    return new_settings


# Content Security Policy
CONTENT_SECURITY_POLICY = {
    "EXCLUDE_URL_PREFIXES": [],
    "DIRECTIVES": {
        "default-src": parse_csp(conf.csp_default_src),
        "script-src":  parse_csp(conf.csp_script_src),
        "style-src":   parse_csp(conf.csp_style_src),
        "img-src":     parse_csp(conf.csp_img_src),
        "font-src":    parse_csp(conf.csp_font_src),
#        "frame-ancestors": [SELF],
#        "form-action": [SELF],
        "report-uri": "/csp-report/",
    },
}
